### ISSUE TITLE
CSS Not import after build

### ISSUE THREAD

**Issue by devbipu** [cmercado93/noUiSliderVue#2]
Hi there, 

I'm using this package with my Vue 3 Vite app. It's working great at the development server. But When I run `npm run build` it's not applying CSS.

**Comment by cmercado93** [comment]
Hi, I apologize for the delay in responding. Could you please provide me with additional details about your development environment? I need to know the version of VueJS you are using, as well as any associated CSS libraries and whether you are using any CSS preprocessors.

**Comment by devbipu** [comment]
Hi, Sorry for the issue. I've fixed.
